spring:
  datasource:
    url: jdbc:postgresql://${TEST_DB_HOST:localhost}:${TEST_DB_PORT:5432}/${TEST_DB_NAME:finopaladar_test}
    username: ${TEST_DB_USERNAME:postgres}
    password: ${TEST_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
